# Generated by Django 6.0.4 on 2026-05-11 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de cita',
                'verbose_name_plural': 'Estados de cita',
                'db_table': '"agenda"."estado_cita"',
                'ordering': ['id_estado'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(db_column='hora')),
                ('hora_fin', models.TimeField()),
                ('observacion', models.TextField(blank=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='citas_barbero', to='seguridad.usuario')),
                ('codigo_cliente', models.ForeignKey(db_column='codigo_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='citas_cliente', to='seguridad.usuario')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.servicio')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='registrado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_registradas', to='seguridad.usuario')),
                ('id_estadoc', models.ForeignKey(db_column='id_estadoc', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.estadocita')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': '"agenda"."cita"',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoCita',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, db_column='cambiado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_cita', to='seguridad.usuario')),
                ('estado_anterior', models.ForeignKey(blank=True, db_column='estado_anterior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_como_anterior', to='citas.estadocita')),
                ('estado_nuevo', models.ForeignKey(db_column='estado_nuevo', on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_nuevo', to='citas.estadocita')),
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Historial de estado de cita',
                'verbose_name_plural': 'Historial de estados de cita',
                'db_table': '"agenda"."historial_estado_cita"',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='BarberoServicio',
            fields=[
                ('id_barbero_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_habilitados', to='seguridad.usuario')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, related_name='barberos_habilitados', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio habilitado por barbero',
                'verbose_name_plural': 'Servicios habilitados por barbero',
                'db_table': '"agenda"."barbero_servicio"',
                'ordering': ['codigo_barbero', 'id_servicio'],
                'unique_together': {('codigo_barbero', 'id_servicio')},
            },
        ),
    ]
