# Generated by Django 6.0.4 on 2026-06-02 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0003_rename_asistencia_column_in_postgresql'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_referencia', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metodo de pago',
                'verbose_name_plural': 'Metodos de pago',
                'db_table': 'ventas_caja_metodo_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanComision',
            fields=[
                ('id_plan_comision', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_barbero', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_barberia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='planes_comision', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Plan de comision',
                'verbose_name_plural': 'Planes de comision',
                'db_table': 'ventas_caja_plan_comision',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
    ]
