# Generated by Django 6.0.4 on 2026-05-11 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': '"seguridad"."rol"',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=128)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('codigo_recuperacion', models.CharField(blank=True, max_length=128, null=True)),
                ('codigo_recuperacion_expira', models.DateTimeField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='seguridad.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': '"seguridad"."usuario"',
            },
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sabado'), ('DOMINGO', 'Domingo')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('hora_inicio_descanso', models.TimeField(blank=True, null=True)),
                ('hora_fin_descanso', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_laborales', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Horario laboral',
                'verbose_name_plural': 'Horarios laborales',
                'db_table': '"seguridad"."horario_laboral"',
                'ordering': ['codigo_barbero', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id_bloqueo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_horario', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Bloqueo de horario',
                'verbose_name_plural': 'Bloqueos de horario',
                'db_table': '"seguridad"."bloqueo_horario"',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('metodo', models.CharField(blank=True, max_length=10)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='codigo_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
                'db_table': '"seguridad"."bitacora"',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaBarbero',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDE', 'Tarde'), ('AUSENTE', 'Ausente'), ('PERMISO', 'Permiso'), ('INHABILITADO', 'Inhabilitado')], max_length=20)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Asistencia de barbero',
                'verbose_name_plural': 'Asistencias de barberos',
                'db_table': '"seguridad"."asistencia_barbero"',
                'ordering': ['-fecha', 'codigo_barbero'],
                'unique_together': {('codigo_barbero', 'fecha')},
            },
        ),
    ]
