# Generated by Django 6.0.4 on 2026-05-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistenciabarbero',
            old_name='observacion',
            new_name='comentario',
        ),
    ]
