# Generated by Django 6.0.4 on 2026-05-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_rename_asistencia_observacion_comentario'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'seguridad'
                      AND table_name = 'asistencia_barbero'
                      AND column_name = 'observacion'
                ) THEN
                    ALTER TABLE "seguridad"."asistencia_barbero"
                    RENAME COLUMN "observacion" TO "comentario";
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'seguridad'
                      AND table_name = 'asistencia_barbero'
                      AND column_name = 'comentario'
                ) THEN
                    ALTER TABLE "seguridad"."asistencia_barbero"
                    RENAME COLUMN "comentario" TO "observacion";
                END IF;
            END
            $$;
            """,
        ),
    ]
